# Generated by Django 5.0 on 2024-02-21 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('adminname', models.TextField(max_length=150)),
                ('position', models.TextField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturerid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lecturername', models.TextField(max_length=50)),
                ('department', models.TextField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mentorname', models.TextField(max_length=50)),
                ('nophone', models.TextField(max_length=12)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studentname', models.TextField(max_length=50)),
                ('nophone', models.TextField(max_length=12)),
                ('password', models.CharField(max_length=10)),
                ('mentorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_System.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(max_length=150)),
                ('date', models.DateField(null=True)),
                ('status', models.TextField(max_length=20, null=True)),
                ('lecturerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_System.lecturer')),
                ('mentorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_System.mentor')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_System.student')),
            ],
        ),
    ]
